//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de.creinbold.FlatShare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("de.creinbold.FlatShare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon app {
            get {
                object obj = ResourceManager.GetObject("app", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Signature {
            get {
                object obj = ResourceManager.GetObject("Signature", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \documentclass[fontsize=12pt]{scrartcl}
        ///
        ///\usepackage[utf8]{inputenc}
        ///\usepackage[ngerman]{babel}
        ///
        ///\usepackage{scrletter}
        ///\LoadLetterOption{DIN}
        ///\LoadLetterOption{sender} % Read sender.lco
        ///
        ///\usepackage{float}
        ///\usepackage{graphicx}
        ///\usepackage{eurosym}
        ///\usepackage{lastpage}
        ///\usepackage{booktabs}
        ///\usepackage{ltablex}
        ///\keepXColumns
        ///
        ///%dashed line
        ///\usepackage{array}
        ///\usepackage{arydshln}
        ///\setlength\dashlinedash{0.2pt}
        ///\setlength\dashlinegap{1.5pt}
        ///\setlength\arrayrulewidth{0.3pt}
        ///
        ///\clubpen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TexBill {
            get {
                return ResourceManager.GetString("TexBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ProvidesFile{sender.lco}
        ///
        ///\KOMAoptions{%
        ///firsthead=true,
        ///fromemail=true,
        ///fromphone=true,
        ///fromfax=false,
        ///fromurl=false,
        ///fromlogo=true,
        ///locfield=wide,
        ///fromalign=right,
        ///fromrule=afteraddress%
        ///}
        ///
        ///\RequirePackage[utf8]{inputenc}
        ///\RequirePackage[ngerman]{babel}
        ///
        /// % TODO: Insert your personal data here
        ///
        ///\setkomavar{fromname}{Anna Vermieterin}
        ///\setkomavar{fromaddress}{%
        ///  Musterstrasse 6\\
        ///  1234 Musterstadt%
        ///}
        ///
        ///\setkomavar{fromemail}{meine@mustermail.de}
        ///\setkomavar{fromphone}{+49~151~11 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TexSender {
            get {
                return ResourceManager.GetString("TexSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \documentclass[fontsize=10pt, landscape]{scrartcl}
        ///
        ///\usepackage[utf8]{inputenc}
        ///\usepackage[ngerman]{babel}
        ///\usepackage{float}
        ///\usepackage{fullpage}
        ///\usepackage[table]{xcolor}
        ///\usepackage{graphicx}
        ///\usepackage{eurosym}
        ///\usepackage{lastpage}
        ///
        ///\usepackage{booktabs}
        ///\usepackage{ltablex}
        ///\keepXColumns
        ///
        ///\clubpenalty10000
        ///\widowpenalty10000
        ///\displaywidowpenalty=10000
        ///
        ///% Header
        ///\usepackage{fancyhdr}
        ///\setlength{\headheight}{15pt}
        ///\setlength{\headsep}{5mm}
        ///\renewcommand{\headrulewidth}{0pt}
        ///\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TexTax {
            get {
                return ResourceManager.GetString("TexTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tenant_transaction_entry(e) ::= &lt;&lt;
        ///	&lt;if(e.IsImportant)&gt;\textcolor{red}{\textbf{&lt;e.Amount&gt;}}&lt;else&gt;&lt;e.Amount&gt;&lt;endif&gt; &amp; &lt;#\#\&gt;
        ///	&lt;if(e.IsOverwriting)&gt;&lt;#\#\&gt;
        ///		\multicolumn{5}{l}{&lt;if(e.IsImportant)&gt;\textcolor{red}{\textbf{&lt;e.Reason&gt;}}&lt;else&gt;&lt;e.Reason&gt;&lt;endif&gt;}&lt;#\#\&gt;
        ///	&lt;else&gt;&lt;#\#\&gt;
        ///		&lt;e.Reason&gt; &amp; &lt;e.Due&gt; &amp; &amp; &lt;#\#\&gt;
        ///		&lt;if(e.OtherYear)&gt;&lt;#\#\&gt;
        ///			\multicolumn{2}{c}{In Steuerbericht &lt;e.OtherYear&gt;}&lt;#\#\&gt;
        ///		&lt;else&gt;&lt;#\#\&gt;
        ///			&lt;e.Net&gt; &amp; &lt;e.Ancillary&gt;&lt;#\#\&gt;
        ///		&lt;endif&gt;&lt;#\#\&gt;
        ///	&lt;endif&gt; \\
        ///&gt;&gt;.
        /// </summary>
        internal static string TexTaxHelpers {
            get {
                return ResourceManager.GetString("TexTaxHelpers", resourceCulture);
            }
        }
    }
}
